### ISSUE TITLE
Test-task list:  milestone - 0928

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#11]
# Task list 

### 2017-09-28

- iOS
- [x]    #3 iOS: 提供一个最新的版本支持iOS 10 及 iOS 11
- [x]    #4 iOS: 已下载中需要有章节目录 
- [x]    #10 iOS: 学习过程打卡分享需求变更

<br>

- Android
- [x]    #6 Android: 课程目录作为独立页面
- [x]    #5 Android: 学习过程打卡分享需求变更

---

- [x]    #7  api-商城：课程的搜索结果只能出现已上架的课程
- [x]    #19 iOS-个人设置： 一键分享APP 
- [x]    #22 IOS-学习系统:在播放界面点击课程目录上的下载按钮出现闪退
- [x]    #24 Android: APP中课程下面，有参与人数的，都去掉
- [x]    #25 iOS: 在app中 显示 “XX参与”的地方，隐藏或删除掉
- [x]    #30 Android-下载:处理旧版本数据

<br>

### 公共测试部分：
- [x]    登入与注册
- [x]    购买与注册、 订单
- [x]    商城 - 点击课程 - 购买 
- [x]    学习系统、下载

<br>

### 数据维护部分：

- [x]   1. 苏斯博士的头图设计和替换，等Ana设计好之后，Jerry维护到系统中
- [x]   2.1 学习过程打卡前，没有出现“坚持打卡，记录学习的每一步”这两个的默认模板，Jerry维护
- [ ]   2.2 学习过程打卡前，没有出现“有始有终，你真的很棒”这两个的默认模板，Jerry维护
- [x]   3. one fish two fish，Dr.Seuss's ABC中没有精选视频，Jerry维护

**Comment by MaryLinker** [comment]
频繁的进行操作或在网络环境很差的情况下播放已下载的课程时，偶尔会出现闪退的现象，重现率极低。

**Comment by daweilv** [comment]
数据维护部分#2，目前部分课程由于合并lesson等操作会出现一些脏数据，导致用户不能达到100%学习进度，不会出现“有始有终，你真的很棒”最后一次打卡的提示，而是“坚持打卡，记录学习的每一步”。
影响：目前不影响用户正常打卡、分享等操作，只是这张图片不是预期图片。
解决方案：
1. 优化后台上传课件前端界面
2. 删除合并 lesson 节点 api 优化，保证删除节点的时候把相关联节点删除干净
3. 清除系统错误数据
预计工作量 4~5 天，建议放到下个版本升级，本版本不作处理。

**Comment by joelin109** [comment]
## 测试版本Switch to正式版本
### 发生如下异常：

- 我的 - ‘立即注册’ 按钮无效
```
没有遵循开发规范，check in 脏代码
```

<br>

- 一键分享 出来的信息 出错。相关issue #19 
```
测试版没有发现到这个问题
```
