### ISSUE TITLE
PC-Tool:  压缩文件加水印, 校验数据,  计算Media的时间等

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#137]
## PC (Tool)
- ### 1. Tool
- [x]   PC-Tool:  压缩音频，图片。 及在图片上面加水印 （#114）
```
注意手机， pad上面需要的图片清晰度不同
```
- [x]  PC-后台-课程管理：课件批量录入  （#21） @Leo
- [x]   PC-Tool：校验图片及Media是否存在，计算Media的时间等 

<br>

- ### 2. 校验数据
- [x]   2.1 PC-Tool：校验数据库中Course数据  (参考#107)
- [x]   2.2 PC-Tool：校验数据库中Lesson数据   (参考#107)
- [ ]   2.3 PC-Tool：校验数据库中Lesson的Media的时间数据 
- [ ]   2.4  PC-Tool：校验数据库中Order 数据
```
Step1： 让48小时以前，未支付的订单失效 
- Leo已经解决历史脏数据
```
- [x]   2.5 PC-Tool：校验数据库中用户学习记录 数据  （#121）
```
用户学习记录(lessonlearn)和学习记录明细表(lessonlearndetail)
```
- [ ]    2.6 PC-Tool：校验数据库中User  数据
- [ ]    2.7 PC-Tool：校验数据库中Share、Coupon等数据合理性
```
t_coupon,
t_pointrecord,
t_shareparam,
t_sharemodaltemplate
```

<br>
<br>

```
提供solution

1. 校验数据应该加个时间Tag， 不要每次都重复校验
2. 校验数据结果：有问题的数据在某个地方可以清晰展示
3. 校验图片及Media：IO读取部分代码使用Golang编写
```

**Comment by joelin109** [comment]
## Solution
- ？

**Comment by itwangxiang** [comment]
### Solution:
1. 获取章节数组
   - SQL:
      ``` sql
      select id,lesson_id,name,parent_id,seq,medias  from t_content 
      where  delete_by is null 
       and parent_id <> '1'
       and type = '2'
      order by lesson_id,parent_id,seq asc
      ```
 2. 比较数据
    - 课件：media 不能为空
    - 音频：每个 lesson 下的 media 数组
       - 时间校验：音频时长是否准确
       - 文件校验：文件路径一定是可访问的，并且是音频
    - 图片：每个 media 下 image 数组
       - 时间校验
         - 第一张一定是：0s
         - 图片时间点不能重复
         - 图片时间点从小到大
         - 图片时间点不能超过音频时长
       - 文件校验：文件路径一定是可访问的，并且是图片

**Comment by itwangxiang** [comment]
## Solution:
### 检查-课件信息
1. 获取章节数组
   - SQL:
      ``` sql
		select a.id,a.lesson_id,a.name,a.medias FROM t_content a where a.delete_by is null and a.parent_id <> '1' 
		and a.type = '2' and a.check_status = '1' and a.lesson_id in (select id from t_lesson where delete_by is null) order by a.lesson_id,a.parent_id,a.seq asc
      ```
 2. 获取文件列表

**Comment by itwangxiang** [comment]
## 校验数据库中Lesson的Media的时间数据 
> 高考英语阅读真题精讲（江苏卷）测试通过

**Comment by itwangxiang** [comment]
## Solution:
### 检查-用户学习记录
1. 获取垃圾数据
``` sql
select a.id,a.lesson_id,a.last_content_id,b.id,b.name,b.lesson_id,b.status,b.delete_by,c.id,c.name,c.status,c.delete_by 
from t_lessonlearn a 
 left join content_lesson b on a.last_content_id = b.id
 left join content_lesson c on b.parent_id = c.id
where a.last_content_id <> b.id
or a.l esson_id <> b.lesson_id
or b.parent_id is null
or b.delete_by is not null
or b.status <> '1'
or c.id is null
or c.delete_by is not null
or c.status <> '1'
```
