### ISSUE TITLE
Test-task list:  V-2.5.1 - 待办列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#159]
#### Test-task list: V-2.0.2 - 正在解决的列表 (#43)

<br>

## 3端
- [ ]  3端: 订单管理 (#146),  地址管理 & 购物车 (#149)
- [ ]  3端-Notification：通知功能 - 由服务器向客户端推送通知信息  (#151)
- [ ]  3端: Lesson 资源文件的加密问题 PC&Android&iOS

<br>

## PC  - `PC-H5: 指3端通用`
- [ ]  数据统计: 学习过程、课程详情页、购买&分享统计 （#127）
- [ ]  PC: 部分用户高考全国卷课程无法学习 (#121) `Need confirm solution`
- [ ]  PC-优化: SEO - 站内优化 (#154)

<br>

## API
- [x]  api-订单支付状态：客户同一门课程支付两次，两次都支付成功  （#53）
- [x]  api：整理一下现有的积分奖励与优惠券规则 `?`
- [ ]  API: 统一分享的积分奖励规则

<br>
