### ISSUE TITLE
PC-安全: 云存储OSS- 课程相关的Media资源迁移 

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#289]
## 已知信息 

https://github.com/bstcine/cine-tasklist/issues/253

```
1. OSS:
原始路径：static-bstcine.oss-cn-shanghai.aliyuncs.com
对外路径：oss.bstcine.com
是否CDN：是
Media_Host：
 - Public 路径：oss.bstcine.com/f/
 - Private 路径：oss.bstcine.com/
    - oss.bstcine.com/img/course_id/
    - oss.bstcine.com/kj/



2. Media 在 Ali 服务器
表：content_lesson_media
image_url： 2017/06/29/11461356SDavrX1.png
未压缩的原始图片：http://www.bstcine.com/f/ + image_url
压缩后的播放图片:  http://gcdn.bstcine.com/img/ + course_id + /f/+ image_url +.jpg

- 未压缩的原始图片有3-4M



3. Media 在 OSS
3.1  LessonMedia
表：content_lesson_media
表中的image_url： 2017/06/29/11461356SDavrX1.png
OSS的原始图片：http://oss.bstcine.com/kj/2017/06/29/11461356SDavrX1.png
OSS的有Cine水印图片：http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg
API提供的image_url：http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg
API提供权限签名的image_url: http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg?Expires=1519640981&OSSAccessKeyId=TMP.AQFqtH_MD6Bq9zZFTMQThNGSRm483zv90jbgTpXFvUBPzV2gdNiP2mNTOty4ADAtAhRfdaz8l6nf-Zk_WrRn4jVHZ1j8owIVAL3hORlUjqa1y5Og1-DeLgJDq44z&Signature=CzJ0cmlrxz2pdqpV9ssvnAHPFVw%3D
播放的480图片:  http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg?x-oss-process=image/resize,w_848,h_480
播放的720P图片:  http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg?x-oss-process=image/resize,w_1280,h_720
播放的1080P图片:  http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg?x-oss-process=image/resize,w_1920,h_1080
播放的1080P+账号水印图片：http://oss.bstcine.com/img/d0114987070071216e0wtYHMZj/2017/06/29/11461356SDavrX1.jpg?x-oss-process=image/resize,w_1920,h_1080/watermark,text_d3d3LmJzdGNpbmUuY29t,type_d3F5LXplbmhlaQ,size_40,t_100,color_000000,g_south,y_10,x_10

建议规则：
播放图片URL：media_host + 'kj' + 'course_id' + '表中的image_url'



3.2  其它（Public）- 比如课程封面
表中的image_url： 2017/04/05/110644110SeY6SAy.png
OSS的原始图片：http://oss.bstcine.com/f/2017/04/05/110644110SeY6SAy.png
API提供的image_url：http://oss.bstcine.com/f/2017/04/05/110644110SeY6SAy.png?x-oss-process=image/format,jpg
显示的缩略图片:  http://oss.bstcine.com/f/2017/04/05/110644110SeY6SAy.png?x-oss-process=image/format,jpg/quality,q_75
显示的480图片:  http://oss.bstcine.com/f/2017/04/05/110644110SeY6SAy.png?x-oss-process=image/format,jpg/resize,w_848,h_480
显示的720P图片:  http://oss.bstcine.com/f/2017/04/05/110644110SeY6SAy.png?x-oss-process=image/format,jpg/resize,w_1280,h_720
```

<br>

### Lesson_Media迁移Ali OSS进度：
- [x]  Step1:  PC-安全: 云存储OSS- 提供工具可对课程相关的Media资源进行迁移 #287 
```
Status：
 - 迁移工具：已提供
 - 课件播放图片：迁移100%（原服务器加过水印的课件图片）
 - 原课件图片：迁移0%
```
- [x]  Step2:  PC-后台管理: 课程管理-制作课件- 上传课件存放到OSS #295
- [x]  Step3:  API-学习系统:  Lesson播放页需要的API使用OSS的资源 #297
```
明确好如下规则：
- 原图的路径：`kj/2018/03/12/xxxxxxxxxx.png` `kj/2018/03/12/xxxxxxxxxx.jpg`
- 水印图路径：`img/courseId/2018/03/12/xxxxxxxxxx.jpg`
```
- [x]  Step4:  PC-学习系统：Lesson播放页-播放的图片需要加上登入账号的水印  #296
- [x]  Step5:  PC-Tool: 检查及确保所有的课件资源都在OSS上
```
- 不能影响线上V2.2.0的iOS APP
- Deadline:  2018-03-15
```

**Comment by joelin109** [comment]
需要Verify确认
- [ ]  Step1:  迁移的课程课件- 480， 720， 1080P显示是否清晰
- [ ]  Step2:  PC-Admin新上传的课件 -  480， 720， 1080P显示是否清晰
- [ ]  Step3:  KJ资源是否都在OSS上面
```
至少一个一个Lesson确认
```

**Comment by joelin109** [comment]
需要Verify确认
- [ ]  Step1:  从ECS迁移过来的课程课件- 480， 720， 1080P显示是否清晰
```
http://oss.bstcine.com/img/42/f/2017/10/11/11092385SaF2kp2.png.jpg

http://oss.bstcine.com/img/42/f/2017/10/11/11092385SaF2kp2.png.jpg?x-oss-process=image/resize,w_848,h_480

http://oss.bstcine.com/img/42/f/2017/10/11/11092385SaF2kp2.png.jpg?x-oss-process=image/resize,w_1280,h_720

http://oss.bstcine.com/img/42/f/2017/10/11/11092385SaF2kp2.png.jpg?x-oss-process=image/resize,w_1920,h_1080


结论：
- 480的不清晰，不要使用
```
- [ ]  Step2:  PC-Admin新上传的课件 -  480， 720， 1080P显示是否清晰
- [ ]  Step3:  KJ资源是否都在OSS上面
```
至少一个一个Lesson确认
```

**Comment by itwangxiang** [comment]
- 待上传的图片
- 已上传的图片
- 加水印的图片
- 各分辨的图片

**Comment by joelin109** [comment]
测试用例
- [ ]  1. Phone: 现有的课程， Lesson播放是否清晰
```
iPhone - 明显的水印只需要一个
```
- [ ]  2. Pad: 现有的课程， Lesson播放是否清晰
- [ ]  3. PC: 有没有办法去掉水印
- [ ]  4. Phone& Pad & PC: 新添加的课程课件， Lesson播放图片是否加载顺利

**Comment by zhuyichun** [comment]
- [ ]  新增加的课件没有‘bstcine 善恩教育’的背景水印
```
http://apptest.bstcine.com/learn/lesson/t0115210795427107ZmrwpaNMc?content_id=t011521079621151VHpZqFr5J8
```
- [  ] PC选择的清晰度固定
```
step1:《傲慢与偏见》lesson1选择1080的清晰度播放
step2:点击lesson2，播放的清晰度切换了
```
