### ISSUE TITLE
H5-学习系统: 学习首页的私塾模块（包含后台管理 ）

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#373]
## 1. PC-Admin： 后台管理      - #389 
- [x] 1.1. 任务基础数据 - 词汇收集  （#394）
- [x] 1.2. 任务基础数据 - 词汇发音  （#411）
- [x] 1.3. 任务基础数据 -习题历史数据整理   （#407）
- [x] 1.4. 任务基础数据 -习题整理&收集   （#400）
- [x] 1.5. 私塾老师 - 分配学生 & 配置授课范围 `Verified`
```
列表：显示是否已配置过课程
```
- [x] 1.6. 私塾学生- 分配作业 `Verified`
- [ ] 1.7. 私塾学生- 分配Chapter习题作业 & 课件词汇作业
 
<br>
<br>
<br>

## 2. App & PC： 学习首页 - `第一版`          
```
- 只针对 ‘开通私塾服务’的用户 ， 才新增显示 `任务`模块 `Verified`
```

#### 2.1.1. 学习首页 - 本周作业 （#406）`√` `Verified`
```
需要调整Lesson简写为规范形式 - P1
```
```
任务列表
任务类型 - 任务名称 - 任务状态

任务类型：词汇、视频、习题、习题（老师的批改）
任务名称：先默认取 课程简写 + Lesson简写
任务状态：未完成/已完成  

-- 提供  '展开' / ‘收起’ 功能， 默认只显示5条。  '展开'显示更多
-- 第一版：某些任务没有对应的链接，点击显示提示框
```

<br>

#### 2.1.2. 本周作业 - 习题测试
- [x] 2.1.2.1 API-学习系统: 习题测试页面需要的数据   - （#409 ）
- [x] 2.1.2.2 本周作业：习题测试 - `2级页面`   - （#399 ） `Verified`
```
A.  课件播放页面： 点击课件对应的习题是相同的连接
B.  普通用户只显示选择题
C.  私塾用户显示选择题或主观题

入口：
本周作业-习题测试
课件学习-习题测验
导师批改-学生作业
```

<br>

#### 2.1.3.  本周作业： 词汇学习
- [x]  2.1.3.1 API-学习系统: Top10000的词汇学习 & 课件的词汇学习  - (#412)
- [x]  2.1.3.2 本周作业： 词汇学习（简易式）- `2级页面`  - (#397)  `Verified`
```
显示编号、英文、中文、读音(非必须）
```
- [x]  2.1.3.3. 本周作业： 词汇测试 - `2级页面`  - (#398) `Verified`
```
词汇测试中，用户的错误选择需要记录下来
```
- [x]  2.1.3.4. 词汇学习的历史记录 - `2级页面`   - （#391 ）
```
与2.1.4 是同一个页面
筛选样式不能`Verified`
```

<br>

#### 2.1.4. 以前作业 - `2级页面`   - （#391 ）
```
A. 提供‘以前所有任务记录’2级页面  

- 可通过·时间或类型·筛选

筛选样式不能`Verified`
```

<br>

#### 2.1.5. 导师主页: 可看私塾学生的作业  & 测试 - （#396） 
```
A. 学生作业- （默认只显示本周作业）
B. 学生测试- （已经完成）
C. 待批改作业 (暂不解决）

代码规范导致不能`Verified`
```

<br>
<br>
<br>

###  交互图：
- 后台管理
https://free.modao.cc/app/vLcyyamVsuAgNkY07TisMETxopGh25A
- 学习首页- `私塾模块`
https://free.modao.cc/app/9DQ7P98BtYiJF6944syPfQweMkKPNZ0

<br>
<br>
<br>

### 测试反馈列表 
- 私塾模块 （#416）
- 习题测试 （核心语法测试 & 课件习题测试 & 导师批改习题）（#417）

**Comment by joelin109** [comment]
## 2018-05-15 会议
1. Lesson的Tag上最好能显示时间
2. 习题类型中，希望可以加入主观题

**Comment by joelin109** [comment]
## Question-疑问

**Comment by daweilv** [comment]
### table t_schedule / t_task

| key | 名称 | 备注 |
| --- | --- | --- |
|id
|title | 标题 | Longman3000基础词汇 /  《动物农庄》第三课 
|object_type | 对象类型 | 1:视频,2:习题,3:习题批改结果,4:单词,9:其他 
|object_id | 对象id | lesson_id, quiz_id, stats_id, word_or_some_id, xxx_id
|object_status | 任务状态 | 0:待完成,1:已完成 
|effective_at | 生效日期
|expire_at | 失效日期
|done_at/complete_at  | 完成日期
|user_id | 指定学生id
|create_at | 任务创建人
|create_by | 任务创建人


Q1:
- [ ] 系统中的两套习题如何兼容


Q2:
- [ ] 词汇类型的 course 的 lesson 结构是怎样的，任务跳转根据什么 key 做跳转，跳转到什么地方

**Comment by zhuyichun** [comment]
##  交互图：https://free.modao.cc/app/9DQ7P98BtYiJF6944syPfQweMkKPNZ0
