### ISSUE TITLE
H5-学习系统: 学习首页的私塾模块- 第2阶段

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#410]
### 1. PC-Admin：基础数据
- [x] 1.1. 抓取网上的习题数据。  (#424)       -`Kim`
- [x] 1.2. PC-Admin: 习题管理- 知识点导入与维护    (#447)
```
- Verified by Jerry
```
- [x] 1.3. PC-Admin: 习题管理- 习题维护 & 提交待审 & 审核通过    (#434)
```
Status: Working

```
- 1.4 收集记录用户在每个课程上的实际学习时间。 具体细节， #386 #387    -`Kim`

<br>
<br>

### 2. 学习系统 
-  [x]  2.1. H5-学习系统: 学习首页-私塾作业完成后打卡  #435
```

```
-  [ ]  2.2. H5-学习系统：课程播放页- 当前页可显示课件播放 & 习题 & 词汇学习 #436     - `David`
```
Status: Working
V2.4.1
```
-  [ ]  2.3. H5-学习系统：课程播放页- 对视频课件可添加维护“知识点”标签   #439    - `David`
```
Status: Working
V2.4.1
```

<br>
<br>

### 3. 学习系统 - 词汇模块 -`Aaron`
-  [x]  3.1. H5-学习系统: 学习首页- 添加top100003门课程  #452 
```
V2.4.1
```
-  [x]  3.2. H5-学习系统: 词汇课程学习- top10000分3门课程（入口在学习首页）      #449 
```
V2.4.1
```
-  [x]  3.3. H5-学习系统: 词汇学习- 词汇起点评估建议  #443 
```
V2.4.1
```
-  [x]  3.4. 本周作业：词汇学习页- 卡片式学习    #426 
-  [ ]  3.5. H5-学习系统: 词汇学习- Chapter&Lesson对应的词汇  #438 
```
V2.4.1
```
-  [ ]  3.6. H5-学习系统：词汇学习模块- 重新调整UI & 整理中文翻译等    #445

<br>
<br>

### 4. 移动APP端 
-  [ ] 4.1. iPad-学习系统：添加私塾模块  #440 
```
V2.4.1
```
- 4.2. iPhone：添加私塾模块
- 4.3. Android：添加私塾模块

<br>
<br>

### 5. 购买与支付 
-  [ ] 5.1. API-购买与支付：支持信用卡跨境支付  #442  - `David`
```
- 使用国际支付宝 - `暂停`
- 信用卡支付
  - 研究Square & Stripe （美国的类似支付宝）的SDK接口，看看是否能集成到我们系统

- 2.4.1
```

<br>
<br>
<br>
<br>

#### 待确认的二级任务主页面
```
针对不同类型：词汇 & 课件 & 习题
- UI待确认沟通
```

**Comment by joelin109** [comment]
## 发布前准备如下
- [x] 1. 私塾导师图片 & 描述信息  - `@Jerry & @Alice`
