### ISSUE TITLE
Test-task list:  V-2.2.0

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#43]
- [x] H5-PC：测试问题反馈列表 - V2.2 （#247）
- [x] iPad-APP: 测试问题反馈列表- V2.2 （#230）
- [ ] iPhone-APP: 测试问题反馈列表- V2.2 （#248）
- [ ] Android-APP: 测试问题反馈列表- V2.2 （#244）

<br>

## 2017-12  - 2018-01

- #### iOS、iPad  -  `V-2.2`
- [x] iPhone-H5: 词汇量测试 -调用H5交互 （#204）
- [x] iPad-商城：首页  -`Working`
- [x] iPad-商城：详情页 (#219)  
- [x] iPad-分享：打卡&详情&App&词汇测试分享
- [x] iPhone-商城: 新版的课程详情页-调用H5交互 (#95)
- [x] iPad-学习系统: Lesson播放页-播放过程添加习题测试 (#232)
- [ ] iOS-Code规范：V2版本-测试问题反馈列表 (#148)

```
Deadline: 2018-01-24
```

<br>

- #### Android  @Kim
- [x]  Android-H5: 词汇量测试设计 (#169)
- [x]  2.5 PC-Tool：校验数据库中用户学习记录 数据 （#121，#137 - 2.5）
- [x] Android-商城：新版的课程详情页-调用H5交互 (#173) 
- [x] Android-学习系统: Lesson播放页-播放过程添加习题测试 （#207）
- [x] Android-H5-个人设置: 地址信息管理 （#206）
```
Deadline: 2018-01-23
```

<br>

- #### PC (Web)  - `V-2.2`
- [x] H5: cine.pwa 前端构建工程持续完善 (#186)  
- [ ] H5: cine.pwa 前端构建-离线缓存  (#202)  @daweilv
#### H5-商城：首页 - 添加课程筛选功能 - UI.Pad (#152, #193)  `Working`
- [x] Pad - Demo 包含Tag选择
- [x] Pad - 推荐
- [x] Pad - 登入后个人已购买信息
- [x] Pad - H5的性能测试

<br>

#### H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情 （#36）
- [x] Demo - Phone/Pad/PC
- [x] UI
- [x] 优惠
- [x] 微信分享后， 显示打开Cine APP
- [x] 登入后UI局部刷新
- [ ] H5的性能测试 - `加载需<1.5秒`
- [x] H5-商城：课程详情页 - 测试问题反馈列表 - V2.0.2 （#222）

<br>

- [x] PC-H5: 词汇量测试设计  （#86, #203）  
- [ ] pc-H5: 词汇量测试-测试记录&词汇量排位图 （#218）@David
```
缺“学龄前” 与 “成人” 数据
```
- [x]  Cine-WeChat：微信公众平台服务号-Template Message （#235）@Leo
- [x] H5-学习系统: Lesson播放页-Media对应的习题测试 (#225，#208) @Kim
- [x] API-购买与支付：购买前如果分享该课程，立刻享受95折 (#160)  `api`
- [x] H5-分享页：Wechat分享里面，用户可领取新人优惠券(5%)，推荐人可获得积分奖励(10%)(#105) 
- [x]  H5-个人设置: 地址信息管理 (#206) @Kim
- [x]  H5-商城：课程详情页 - 可扫二维码跟踪 (#246) @Leo
- [x]  H5-购买与支付：PC端的结算中心页面需要与APP端一致 (#238)
- [x] PC-学习系统：账户需要强制进行手机号绑定 - H5 (#233)
- [ ]  开通课程通知邮件：对于需要快递的商品，在通知邮件中加上收件人的信息 @David
- [ ]  H5-个人设置: 我的优惠券- 显示优惠券信息，与app类似 (#122) @Kim

<br>

```
H5 - @David, API - @Leo
```

<br>
<br>

---

- #### PC (Tool)：压缩文件加水印, 校验数据, 计算Media的时间等  （#137）@Kim
- [ ]   PC-Tool:  压缩音频，图片。 及在图片上面加水印 （#114） 
- [x]  PC-后台-课程管理：课件批量录入  （#21） 
- [x]  PC-Tool: 校验数据库中Course、Lesson 数据合理性 （#）参考#107 `Working`
- [ ]   PC-Tool: 校验数据库中`Order`、`Share`、`User` 、`Coupon`等数据合理性 
- [ ]   PC-Tool: 校验图片及Media是否存在，计算Media的时间等 （#）
- [x]   PC-Tool: 批量获取课程习题和单词 (#195) 

<br>

<br>

<br> 
<br> 
<br> 

## 明显需要改进的问题
- [ ]   测试文档: 测试Case的细化列表 （#128）`Working` @Marry
- [ ]   测试文档: App页面对应的API请求  @zhuyichun 
- [x]  Bug问题跟踪
- [x]  测试环节：测试力度，测试用例，问题反馈清单
- [x]  测试机器，每个平台至少3台（不同Size）
- [ ]  配置文档: Server Web Admin [后台配置](https://github.com/bstcine/help/wiki/Server-Web-Admin-%E5%90%8E%E5%8F%B0%E9%85%8D%E7%BD%AE)  @zhuyichun 

<br> 

<br> 

- #### 反馈的问题: 2017-11：小助手反馈的问题列表 (#145)
- ### Test-task list: V-2.1.1 - 待办列表 (#159)

<br> 

### 技术规范 - JS：
- [ ]  1.  Server - Util:  不支持 async/await
- [ ]  2.  Client - Component:  不支持 redux
- [x]  3. PC-H5：不支持Html文件直接打开
- [ ]  4. PC-H5：不支持Cache

**Comment by joelin109** [comment]
## Code调整
- [ ]    #42 api-Code规范：提供V2版本的api 
- [ ]    #38  iOS-Code规范：提供iOS项目的框架 
- [ ]    #35 iOS-Code调整：把所有的Model都放在统一的Model目录中

**Comment by joelin109** [comment]
### 公共测试部分 - V-1.1.3：
- [ ]    注册新账户 （可先删除相应的测试账户）
- [ ]    登入、我的
- [ ]    购买与注册、 订单
- [ ]    商城 - 点击课程 - 购买 
- [ ]    学习系统、下载

```
Build 1.2.1
```

**Comment by joelin109** [comment]
公共测试部分 - V-1.1.6：

 注册新账户 （可先删除相应的测试账户）
 登入、我的
 购买与注册、 订单
 商城 - 点击课程 - 购买
 学习系统、下载

**Comment by joelin109** [comment]
## 2017-11-6  >> 11-10
  - [ ] [pc-H5: 词汇量测试设计 #86](https://github.com/bstcine/cine-tasklist/issues/86) @David
```
Status：已完成基本demo， 等待最终的UI和明确的算法
```

  - [ ] [pc-后台管理: 词汇量测试设计 - 文档数据导入 #115](https://github.com/bstcine/cine-tasklist/issues/115) @leo
  - [ ] [ 安卓-下载：已下载课程目录显示方式 #49](https://github.com/bstcine/cine-tasklist/issues/49) @kim
  - [ ] [iOS-Code规范：把现有的功能迁移到V2 #84](https://github.com/bstcine/cine-tasklist/issues/84) @Aaron 
  - [ ] PC-Tool: 压缩音频，图片。 及在图片上面加水印  [(#114)](https://github.com/bstcine/cine-tasklist/issues/114) @kim
