### ISSUE TITLE
Realese-v2.4.2: 测试发现新问题的反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#457]
### B. iPadAPP: V-2.4.2 - `2018-12-13` - `Aaron`  #474 
```
Status: 提交审核中

-等待测试 -2018-11-23
-测试反馈bug #474  -2018-11-26
-解决bug，提交新的版本，等待测试  -2018-11-27
-增加功能: 头像上传到oss，sts信息加密   -2018-12-10
-测试完成，开始准备提交工作  -2018-12-13
-已提交审核  -2018-12-14


deadline : 2018-11-27
-更新deadline：2018-11-30
-更新deadline：2018-12-05
-更新deadline：2018-12-13
-更新deadline：2018-12-14
```

### C. AndroidAPP: V-2.4.2（包含私塾模块） - `2018-12-13` - `Kim`  
- [x] C1. 添加PV& UV 统计数据
- [x] C2. 快速注册时，需增加可选择国家号码的选项 （参考H5）  #343 
- [x] C3. APP上的图片显示需要支持绝对路径（包含https）
- [x] C4. APP上的头像需要上传到OSS
```
status：已发布 - 2018-12-14
```

### D. H5:  添加PV& UV 统计数据 - 2018-11-28 -`David`
```
商城首页
详情页 - （不同的课程需要跟踪记录）
播放页 - （已经添加）

Status：已解决， 待Verify

Deadline：
2018-11-28 10：00
```

<br>
<br>

## P0           - `发布后发现的P1Bug`  -  `立马解决`
- [ ] 01. 学习系统：课件播放页- 记录每个Lesson学习时长不对，学习时长统计结果都是0 - `Kim`
```
三端都有同样的问题

- From Jerry
```
- [x] 02.  Android-商城:  课程详情页- 点击试听，然后点击全屏显示，出现白屏（错误异常)。 - `Kim`
```
安卓APP：
点击商城→托福口语精讲课程→试听→全屏显示，显示白屏；
无论wifi还是4G情况下都是这样，并且其他课程都是这样。

-Jenny
```

<br>
<br>

## P1           - `Must fix`
- [x] 1.1.  PC-Admin：有赞方式开通的订单，也需要发订单通知邮件 - `Kim`
```
- 提醒方式与直接在Cine购买一样
- From John

开发新增模块
1. 新用户创建短信通知
2. 课程订单创建邮件与短信通知
```
- [x] 1.2.  用户数据：用户表中有许多重复手机号的数据 -   #476 - `p3` - `Verified`
```
大多数重复手机已解决
```
- [x] 1.3.  H5-PWA：所有的图片显示需要支持绝对路径  - `Verified`
```
如：课程详情页， 头像， Banner， Tab图标等等
```

**Comment by joelin109** [comment]
## For Jerry
### 紧急测试


<br>

### 紧急交互
- [x] 2.1.  后台管理： 2级页面-口碑好评   #472 


<br>

### 紧急数据维护
- [ ] 3.1 后台配置：?

**Comment by joelin109** [comment]
## 已解决列表
### www
#### 小补丁2.4.02   - `2018-09-29`
- [x] 1.  私塾模块-导师: 导师分配待改进问题 , #444  - `David` - `Verified`
- [x] 2. 网站数据统计分析: 课程播放学习  #460  - `Kim` - `Verified`
```
每次H5&iOS App&Android App课件学习，表“stats_lesson_learn_log”都有记录
```
- [x] 3. 字母很长(<=15个) 的单词页可以正常显示    - `Aaron` - `Verified`
- [x] 4. 购买与支付：支持信用卡跨境支付  #442 
```
APP：商城价格显示人民币标识  -bug
```

- [x] 1.1.  PC-Admin：Lesson的习题导入 - `Kim`  - `Verified`
```
Step1：导入Lesson 习题的文档
Step2：该Lesson以前导入的习题都设置为‘无效’
Step3：该Lesson 的新习题 会显示在 ‘Lesson测验’ 中

- 已发布官网
```

<br>

#### 小补丁2.4.03   - `2018-10-24`
```
C1. 学习首页-“核心词汇”
C2. 学习首页-“善恩核心10000词汇”学习页面
C3. “善恩核心10000词汇”学习页面-起点评估
C4. 卡片式学习

澄清: 
- Nancy二维码代码已屏蔽
- 课程咨询二维码 存在多次水印
```
- [x] 1.1. 学习系统：“核心词汇”-卡片式学习中文翻译应该显示在中间且左对齐
- [ ] 1.2.  PC-Admin：批量注册用户 - `P1` - `需求` - `Kim`
```
系统路径：
- 系统管理 》用户管理 》批量用户创建

需求1：- P1
Step1：点击“批量创建”Button，导入“批量注册用户”文档，创建批量用户。
Step2：界面上显示：本次导入手机关联的所用户的账号列表 (分2部分：新的 + 已有的）

逻辑澄清：
- 1. 文档中：批次号、手机号非空
- 2. 文档中：如果账号为空，使用“手机号”
- 3. 文档中：如果密码为空，使用“手机号的后6位
- 4. 文档中：如果昵称为空，使用“姓列+名列”
- 5. 如果手机号系统已经有，Update 改用户的”批次号 & Update时间“

需求2：- P2
Step1：输入“批次号”， 点击“导出”Button，导出“批次号批量注册用户”文档。
Step2：导出文档列：“bath_no | login | nickname | phone | remark | create_date | update_date”

```
- [x] 1.3-3.2. 学习系统：私塾账号登录学习首页只显示"每日一词"，刷新当前页面，其他信息才显示出来  -`Verified`
```
浏览器：Safari
Deadline: 2018-10-15

目前状态：
不需用刷新即可显示出来。

遗留新bug
即页面退出登录，重新点击“学习首页”也有一定几率不需重新登录，
- 清除缓存后正常
```

- [x] 1.4. 搜狗浏览器和IE不能正常访问官网-Verified
```
by willing

备注：
IE & 360 & 搜狗：确保购买流程能走通
测试反馈：
- IE11： win7  64位 首页蓝屏 - `-Verified`
- IE11：美元支付失败
- 搜狗浏览器 -`Verified`
- 360：  -`Verified`

```
- [x] 1.5：批量开通课程添加可选填字段‘应付金额’、‘有效期’  -  `Kim` -`Verified`
- [x] 1.6. PC-后台管理: 习题管理- 课件的知识点导入与维护 #464

<br>
<br>

#### 小补丁2.4.04   - `2018-11-03`
- [x] 1.1.  PC-Admin：私塾任务分配-添加作文简述 - `David`
```
- 作文简述: 如果没有写，学生点击作文作业不用弹框提示 （P3）
```

- [x] 1.2.  课件播放页：添加 “课程咨询Nancy老师”二维码 - `P1`  - `David` 
```
位置：分享打卡的左边，文字颜色与分享打卡的背景色一样
效果：与首页的“课程咨询一样”

- 微信“扫一扫”, 联系Nancy老师
- (微信号：WEINANQIU)
- PWA的代码路径：src/client/component/QRHelp/QrNancy.js

测试反馈：
“WEINANQIU” 应该改为 “WELNANQLU”

```
- [x] 1.3.  课程详情页：显示“抽奖活动” - `P1`  - `David`
```
- PWA中：把与推荐得积分相关的代码与图片都清除（保持代码干净）
- 后台配置：可以设置那些课程有“抽奖活动”

- 点击抽奖，打开的链接：temp/lottery?allowopen=1
```
- [x] 1.4. 学习首页-我的课程：调整课程封面大小，使右边的文字可显示4行 - `P1`  - `David`- Verified
```
- 课程名字：最多显示2行
- 进度：-
- 有效期 （Phone版也显示出来，字体样式与‘进度’一致）
```
- [x] 1.5.  私塾分享数据：学生的词汇量总数有个最低值   - `David`
```
一个小时最少学20个词汇（3分钟最少学1个）

测试反馈：默认词汇量不对 - Fix
```
- [x] 1.6.  核心词汇数据：词性J没有匹配到的需要John提供 - `Verified`
```
```
- [x] 1.7.  PC-Admin：批量注册用户 - `P1` - `需求` - `Kim` `Verified`
```
系统路径：
- 系统管理 》用户管理 》批量用户创建

需求1：- P1
Step1：点击“批量创建”Button，导入“批量注册用户”文档，创建批量用户。
Step2：界面上显示：本次导入手机关联的所用户的账号列表 (分2部分：新的 + 已有的）

逻辑澄清：
- 1. 文档中：批次号、手机号非空
- 2. 文档中：如果账号为空，使用“手机号”
- 3. 文档中：如果密码为空，使用“手机号的后6位
- 4. 文档中：如果昵称为空，使用“姓列+名列”
- 5. 如果手机号系统已经有，Update 改用户的”批次号 & Update时间“

需求2：- P2
Step1：输入“批次号”， 点击“导出”Button，导出“批次号批量注册用户”文档。
Step2：导出文档列：“bath_no | login | nickname | phone | remark | create_date | update_date”

澄清：
已经发布官网
```
- [x] 1.8.  我的学习-词汇学习: 卡片式 - 单词(所有单词)点击发音图标没有声音。- `Aaron` - `Verified`
- [x] 1.9. 商城: 课程咨询- 点击显示联系善恩小助手2（微信号与二维码）
```
- 整个网站
```



<br>
<br>

#### 小补丁2.4.2   - `2018-11-30`
- [x]  1.1. 在课程详情页面时，如果弹出登录框，登录后，试听视频会自动播放。- `David` - `Verified`

<br>
<br>

#### 小补丁2.4.2.1   - `2018-11-05`
- [x] 1.4.  账号权限:   当用户查看微信朋友圈的分享信息，比如`课程详情页`。 APP&PC端的账号不要被退出- `David` - Verified
```
Step1：WeChat Phone端：通用授权登入的， 不要影响该账号在其它端的正常使用
Step2：最终Solution 待确认
```
- [x] 1.5.  个人设置:  社交账号- 提供WeChat绑定的功能 - `David` - `Verified by Jenny/Eelin` 
- [x] 1.6.  权限授权:   PC端微信登入关联未注册的手机号后，用户第二次登录时不太清楚学习账号&输入密码， - `David` - `Verified by Eelin/Jenny`
```
Solution：
- 在关联新手机号的后，继续让用户”设置密码“。
```

<br>
<br>

### Dev

**Comment by zhuyichun** [comment]
### 3

- [ ] 3.1、私塾单词任务：词汇学习页面UI序偶乱
[查看图片](https://user-images.githubusercontent.com/20130469/45140282-db050800-b1e4-11e8-9d6d-66b7161e20e8.jpeg)
```
iPad2
- From 小助手
```
-  3.2-  某一时间段网站卡的厉害
-  3.3-  某一时间段登录页面需要数次登录才登录成功
-  3.4-  私塾模块：老师分配任务，不能显示这个课程的所有目录树
```
safari浏览器
-- from 赵晴老师

澄清：换个浏览器就好了
```
- [ ] 3.5-  私塾模块：学生已经完成这个单词任务又显示为待完成
```
step 1：老师布置了9/16-9-16的单词任务,学生完成了9/16-9-16的单词任务
step 2:老师9/16-9-16的打开编辑页面，然后点击保存
结果：9/16-9-16的单词任务状态被还原为未完成状态
```

**Comment by Anawangqi** [comment]
![02 -0](https://user-images.githubusercontent.com/32318334/45670705-0decbb80-bb56-11e8-803f-f1f94b692c93.png)

**Comment by Willingkong** [comment]
1. 代理商发放新人95折优惠券规则
   问题：用户下单私塾订金后，在购买视频课程时就不能使用代理的新人95折优惠券
   建议：新人95折优惠券在查询用户是否有付费超过0.1元的历史订单是，只查询视频课程的购买记录。

**Comment by joelin109** [comment]
## 小补丁2.4.02   - `2018-09-29`
- [x] 1.  私塾模块-导师: 导师分配待改进问题 , #444  - `David` - `Verified`
- [x] 2. 网站数据统计分析: 课程播放学习  #460  - `Kim` - `Verified`
```
每次H5&iOS App&Android App课件学习，表“stats_lesson_learn_log”都有记录
```
- [x] 3. 字母很长(<=15个) 的单词页可以正常显示    - `Aaron` - `Verified`
- [x] 4. 购买与支付：支持信用卡跨境支付  #442 
```
APP：商城价格显示人民币标识  -bug
```

**Comment by zhuyichun** [comment]
- 1.神奇树屋2测试题测试结束点击‘答题结束’没有反应
```
pad web
```
- [ ] 2、 H5-商城：切换tabs后类别和阶段选项还原为全部  -P2
-  3.手动开通订单，备注为必填项
- [ ] 4.批量注册用户对于系统中已经存在手机号仍然有一定概率注册成功 -BUG -P1
[createusers 下午1.49.10.xls.zip](https://github.com/bstcine/cine-tasklist/files/2477176/createusers.1.49.10.xls.zip)
- [ ] 5 用户订单有效期转换后系统自动同步订单
- [ ] 6 私塾任务习题标题字体建议改下，支持大部分标题在一行

**Comment by joelin109** [comment]
## 测试反馈-核心词汇模块
### 1. 词汇课程页面-善恩核心词汇10000
- [x] 1.1 词汇课程页面：当最新学习记录为第一个时，列表未展开  - `Joe`
```
Step1：起点测试评估结果为1，返回“词汇课程页面”.
Step2:  返回“学习首页”，点击“核心词汇”
Step3：词汇课程页面：第一级列表未展开（错误）

- 应该展开
```

<br>
<br>

### 2. 词汇学习页面
- [ ] 2.1. 学习首页→核心词汇→善恩核心词汇10000词1-1000→第一组→立即学习：右上角的 “帮助” 按钮无法点击。-Jenny
- [ ] 2.2. IOS app，学习首页→核心词汇→善恩核心词汇10000词1-1000→第一组→立即学习，点击“自动播放”，选择自动播放的时候，英文单词出现时间大概2-3秒，但是翻到中问后，中文只出现1秒，立刻到下一个，从体验上，感觉中文出现的时间是不是有点短… - Alice
```
```
- [x] 2.2. 卡片式：点击已认识，单词的状态没有立即更新，而是在显示下一个单词时才更新 -aaron
```
更新此功能存在一定的风险，建议在下一个版本更新
```
- [ ] 2.3. 卡片式：点击已认识，建议直接显示下一个
```
这是需求， 待确认
```

**Comment by JENNY-BSTCINE** [comment]
## iOS APP
### 1. 私塾模块
- [ ] 1.1、 IOS app，点击我的学习→本周作业→作文，作文题目比较长的时候显示不全。
建议：题目显示不全时，点击题目，弹出框框，显示完整的题目信息。-Alice
- [x] 1.2、 IOS app，本周作业→点击 习题 魔法手指 lesson1/Exercise PDF, 出现的提示语请改为：请登录网址 www.bstcine.com/learn 下载对应习题 -Alice
- [x] 1.3、IOS app，点击学习首页→神奇树屋1课程→课程目录：客户服务 和版本申明的格式应跟PC端一致。PDF习题需要显示，点击出现弹窗，提示语为：请登录网址 www.bstcine.com/learn 下载对应习题  ；(适用于所有课程）-Alice
- [x] 1.4、 IOS app， 点击 我的学习→本周作业→单词 10000基础词汇 No.164~No.174 → 立即测试：第一次测试完毕成绩为80%，任务状态没打勾；第二次重新测试，成绩为90%，任务状态仍然没打勾。-Jenny

### 2、词汇模块：
- [ ]  2.1、点击 我的学习→本周作业→单词 10000基础词汇 No.164~No.174 → 立即测试，start，出现的选项中 其中两个为，开始，启动 以及 开始，让人不知道如何选择。这10个单词列表里，有start和begin两个近义词，因此测试时出现的抓取的选项数据可能出现一个词两个选项的词义相近。
建议：词义相近的两个词不要放在一起学习，容易引起混淆。有待进一步讨论。-Alice

**Comment by zhuyichun** [comment]
- [ ] 1.用户账号密码‘是否需要重置密码’设置为是，用户登录时提示错误
- [x] 2、核心词汇测试的的背单词起点，会在我的-我的测试：我的词汇量测试生成一条记录 -P1
- [x] 3、播放动物农庄lesson3最后一个tag结束后自动弹出动物农庄测试题（内容空只有标题）
- [x] 4、最后一个tag播放结束没有弹窗

**Comment by zhuyichun** [comment]
### 4.后台管理
- [x] 4.1、后台管理-批量开通课程失败  -p1 -bug
- [ ] 4.2、后台管理-课程编辑：修改后课程图片丢失  -bug
- [ ] 4.3 双十一活动已过期的课程再次参加同类型活动还是提示“ 已开通同类型活动!”

**Comment by JENNY-BSTCINE** [comment]
商城
在点击神奇树屋套餐立即购买后，页面显示各个课程的价格跟目前官网课程对应的价格不符。其他套餐课程也有这个情况。-P1 Jenny

**Comment by Willingkong** [comment]
目前：在课程详情页面时，如果弹出登录框，登录后，试听视频会自动播放。
建议：试听视频只有在用户点击的时候再播放，不要有自动播放的情况。

**Comment by zhuyichun** [comment]
### dev
- [ ] 1、注册页面没有‘已有账号’按钮

**Comment by joelin109** [comment]
## v2.4.1 第四次补丁 官网测试反馈
- [ ] 1.1、购买-支付：&&&&&
- [ ] 1.2、PC官网首页 英文名著阅读和托福/SAT/AP 筛选标签下的“听力”标签下没有合适课程的标签不需要显示出来。请顺便检查一下其他有没有标签下课程为空的情况，如有，这些标签也不需要显示。
- [ ] 1.3   课程学习页面，目录里客户服务的那一栏，二维码图片应修改完最新的图片。
- [ ] 1.4   将ios中课程详情页分享至微信好友，好友在微信中打开链接并登陆付款，选择“支付宝支付”，跳转至手机中的其他浏览器，显示系统异常，无法成功支付。（可能的原因：微信浏览器中登陆账号与其他浏览器中登陆账号不一致） - Alice

**Comment by iYuanYuan2** [comment]
## v2.3.4 第四次补丁 官网测试反馈
### ios

**Comment by JENNY-BSTCINE** [comment]
### 2、安卓 
- [ ] 2.1 优化：我的下载里没有“正在下载”和“已下载”标识，建议增加区分；-Eelin

### 安卓和IOS：
- [ ] 1、已经被退出后的nologin提示不明显，建议直接弹出登录界面
```
Alice 将提供提示语
```
- [ ] 2、h5购买界面可以下拉选择优惠券码  - 优化

**Comment by zhuyichun** [comment]
- [ ] 1、已经被退出后的nologin提示不明显，建议直接弹出登录界面
- [ ] 2、h5购买界面可以下拉选择优惠券码  - 优化

**Comment by zhuyichun** [comment]
andr 积分规则页面显示问题

**Comment by JENNY-BSTCINE** [comment]
安卓
1、点击某门课程的目录里的 版权声明、客户服务、学习资料下载、本章习题这些页面以及积分规则的页面，页面显示奇怪，一页显示不全。

**Comment by zhuyichun** [comment]
- [ ] 1.访问有个人头像的页面，头像有2次刷新如个人中心 -jerry

**Comment by itwangxiang** [comment]
# 手机重复数据处理
```mysql
-- 新增字段
alter table d_user_order 
add column phone_repeat_count varchar(11) COMMENT '手机重复次数',
add column point varchar(50) COMMENT '积分',
add column coupon_count varchar(50) DEFAULT '0' COMMENT '优惠券数',
add column is_school varchar(1) DEFAULT '0' COMMENT '是否学校账户[0:否,1:是]',
add column is_need_merge varchar(1)  DEFAULT '1' COMMENT '是否需要合并[0:否,1:是]';

-- 积分
select uo.phone,uo.login,uo.name,u.point from d_user_order uo left join t_user u on uo.user_id = u.id;
update d_user_order uo left join t_user u on uo.user_id = u.id set uo.point = u.point;

-- 优惠券
select * from d_user_order uo left join (select user_id,count(*) count from t_coupon where delete_by is null and user_id is not null group by user_id) c on uo.user_id = c.user_id where c.count is not null;
update d_user_order uo left join (select user_id,count(*) count from t_coupon where delete_by is null and user_id is not null group by user_id) c on uo.user_id = c.user_id set uo.coupon_count = c.count
where c.count is not null;

-- 手机号重复次数
select o.*,(select count(t_o.phone) from d_user_order t_o where t_o.phone = o.phone group by t_o.phone) phone_count from d_user_order o;
update d_user_order as uo set uo.phone_repeat_count = (select temp.count from (select count(phone) count,phone from d_user_order group by phone) as temp where temp.phone = uo.phone);

-- 是否学校账户
select * from d_user_order where login  like 'jy%' or login like 'lf%';
update d_user_order set is_school = '1' where login  like 'jy%' or login like 'lf%';

-- 是否需要合并
select phone,GROUP_CONCAT(login),GROUP_CONCAT(name),length(replace(GROUP_CONCAT(login),login,'')) > 1 as login_is_diff,length(replace(GROUP_CONCAT(name),name,'')) > 1 as name_is_diff,!(length(replace(GROUP_CONCAT(login),login,'')) > 1 and length(replace(GROUP_CONCAT(name),name,'')) > 1) as is_need_merage from d_user_order where is_school = '1' group by phone;
update d_user_order as uo set uo.is_need_merge = (select temp.is_diff from (select phone,!(length(replace(GROUP_CONCAT(login),login,'')) > 1 and length(replace(GROUP_CONCAT(name),name,'')) > 1) is_diff  from d_user_order where is_school = '1' group by phone) as temp where temp.phone = uo.phone) where uo.is_school = '1';

-- 需要合并的数据
-- 学校数据
select user_id,phone,login,password,name,is_need_merge,is_school,point,coupon_count,nickname,islearn,expire_at,coursename from d_user_order where phone_repeat_count = '2' and is_need_merge = '1' and is_school = '1';
-- 非学校数据
select user_id,phone,login,password,name,is_need_merge,is_school,point,coupon_count,nickname,islearn,expire_at,coursename from d_user_order where phone_repeat_count = '2' and is_need_merge = '1' and is_school <> '1';

-- 不需要合并的数据
select user_id,phone,login,password,name,is_need_merge,is_school,point,coupon_count,nickname,islearn,expire_at,coursename from d_user_order where phone_repeat_count = '2' and is_need_merge <> '1';

```

**Comment by zhuyichun** [comment]
## 20181128 测试反馈
- [x] 1.首页登录后，鼠标悬浮在‘我的’，点击交互样式不对[1543383773905](https://user-images.githubusercontent.com/20130469/49131658-f3804c80-f313-11e8-9858-f3770301d926.jpg)
-  2.未绑定微信的账号通过账号登录，点击我的社交，显示社交账号：暂未绑定微信。是否添加绑定按钮[1543385521439](https://user-images.githubusercontent.com/20130469/49132493-9ab2b300-f317-11e8-8d8b-aa87c6f95850.jpg)
```
没有这个需求
```
- [ ] 3.在pad浏览器中社交账号、绑定手机页面样式不对[wechatimg9](https://user-images.githubusercontent.com/20130469/49133022-7c4db700-f319-11e8-88d3-efd2108f7b39.jpeg) - `p3`
- [x] 4.个人中心-我的反馈- 错误：  提交后提示网络异常 - `Kim`
-  5.网站header不统一，首页和关于善恩使用的头部就不一致 
```
官网有同样问题
```
- [x] 6.口碑图片点击更多跳转到口碑好评页面蓝屏
- [x] 7.pad端二级页面没有head
- [x] 8.二级页面录课老师添加‘更多’按钮

**Comment by JENNY-BSTCINE** [comment]
2018/12/12
安卓APP：点击商城→托福口语精讲课程→试听→全屏显示，显示白屏；无论wifi还是4G情况下都是这样，并且其他课程都是这样。-Jenny

**Comment by zhuyichun** [comment]
###  安卓测试反馈
- [ ] 2、试听课程的全屏，不能切换成 ”横屏“，感觉视觉体验和不全屏没啥两样
