### ISSUE TITLE
H5-学习系统: 私塾模块&词汇模块&数据统计分析- 第3阶段 

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#459]
### 1. PC-Admin：基础数据  -`Kim`
- [x] 1.1. PC-Admin: 习题管理- 知识点&习题维护的测试问题反馈列表    (#451)
- [ ] 1.2 收集记录用户在每个课程上的实际学习时间。 具体细节， #386 #387    

<br>
<br>

### 2. 学习系统 - `David`
-  [ ]  2.1. H5-学习系统：课程播放页- 当前页可显示课件播放 & 习题 & 词汇学习 #436     
-  [ ]  2.2. H5-学习系统：课程播放页- 对视频课件可添加维护“知识点”标签   #439    
```
```

<br>
<br>

### 3. 学习系统 - 词汇模块 -`Aaron`
-  [x]  3.1. H5-学习系统: 学习首页- 添加top100003门课程  #452 
-  [x]  3.2. H5-学习系统: 词汇课程学习- top10000分3门课程（入口在学习首页）      #449 
-  [x]  3.3. H5-学习系统: 词汇学习- 词汇起点评估建议  #443 
-  [ ]  3.4. H5-学习系统: 词汇学习- Chapter&Lesson对应的词汇  #438  - `P3`
-  [x]  3.5. H5-学习系统：词汇学习模块- 重新调整UI & 整理中文翻译等    #455 - `P1`

<br>
<br>

### 4. 移动APP端 
-  [x] 4.1. iPhone-学习系统：V-2.4.1（包含私塾模块） #454
```
Deadline: 2018-10-25 (提交审核）

Status：提交审核中
```
-  [ ] 4.2. iPad-学习系统：添加私塾模块  #440 
-  [x] 4.3. Android-Phone&Pad：V-2.4.1（包含私塾模块） #463
```
Deadline: 2018-10-25 (发布）

Status：随时发布，等iOS审核通过
```

<br>
<br>

### 5. 购买与支付 
-  [x] 5.1. API-购买与支付：支持信用卡跨境支付  #442  - `David`
```
- 使用国际支付宝 - `暂停`
- 信用卡支付
  - 研究Square & Stripe （美国的类似支付宝）的SDK接口，看看是否能集成到我们系统
```

<br>
<br>

#### 6.1. 用户课程学习情况  
用户 | 课程 | Lesson | 开始学习时间 | 在线学习时长 | IP所在城市
-- | -- | -- | -- | -- | --

- [x]  6.1.1 用户课程学习课件的API #386
- [x]  6.1.2 AndroidAPP- 课件播放页： 调用 “课件学习时间”API        #463
- [ ]  6.1.3 H5-课件播放页： 调用 “课件学习时间”API
- [x]  6.1.4 iOSAPP-课件播放页：调用 “课件学习时间”API            #454

#### 6.2. PV & UV & IP
```
每天/月-某些页面(课程详情页 & 首页 & 课件播放页）：
PV（Page View）： 页面访问量
UV（Unique Visitor）：用户访问数 （没登入也算）

选择一个主流的来源统计分析平台，如Umeng等
```
##### 极光统计 SDK 文档：[Android](http://docs.jiguang.cn/janalytics/client/android_guide/)、[IOS](http://docs.jiguang.cn/janalytics/client/ios_guide/)

- [ ]  6.2.1 AndroidAPP: 添加的跟踪PV&UV的代码            #463

```java
 // 页面统计
JAnalyticsInterface.onPageStart(this, this.getClass().getCanonicalName());
JAnalyticsInterface.onPageEnd(this, this.getClass().getCanonicalName());

 // 浏览事件
BrowseEvent bEvent = new BrowseEvent();
bEvent.setBrowseId(url);
bEvent.setBrowseName(title);
bEvent.setBrowseType("h5");
JAnalyticsInterface.onEvent(this, bEvent);
```
- [ ]  6.2.2 H5: 添加的跟踪PV&UV的代码
```
需要在被统计的页面 插入 `统计代码`:

现有课件播放页&登入页的统计代码:
<div style="display: none">
    <script src="https://s13.cnzz.com/z_stat.php?id=1261976258&web_id=1261976258" language="JavaScript" ></script>
</div>
```
- [x]  6.2.3 iOSAPP: 添加的跟踪PV&UV的代码        #454
```
必须配对调用beginLogPageView:和endLogPageView:两个函数来完成自动统计
启动SDK:
        let config = JANALYTICSLaunchConfig()
        config.appKey = JPUSHAppkey
        config.channel = RegisterChannel
        config.isProduction = isDeveloper.boolValue
        JANALYTICSService.setup(with: config)

pv:
        JANALYTICSService.startLogPageView(pageName)
        JANALYTICSService.stopLogPageView(pageName)

event:
        let browseEvent = JANALYTICSBrowseEvent()
        browseEvent.name = browseName
        browseEvent.contentID = path
        browseEvent.type = "h5"
        browseEvent.duration = duration
        JANALYTICSService.eventRecord(browseEvent)
```

**Comment by itwangxiang** [comment]
# 开发

## SQL

- [ ] WWW
- [ ] DEV

```mysql
DROP TABLE IF EXISTS `t_school`;
CREATE TABLE `t_school` (
  `id` varchar(30) NOT NULL COMMENT 'ID',
  `name` varchar(100) NOT NULL COMMENT '学校名',
  `short_name` varchar(100) NOT NULL COMMENT '学校简称',
  `logo_img` varchar(100) NOT NULL COMMENT 'logo 图',
  `bg_img` varchar(100) NOT NULL COMMENT '背景图',
  `href` varchar(100)  COMMENT '访问地址',
  `seq` int(11) NOT NULL COMMENT '排序号',
  `status` varchar(1) NOT NULL DEFAULT '1' COMMENT '状态 [隐藏:0,显示:1]',
  `create_at` varchar(24) DEFAULT NULL COMMENT '创建日期',
  `create_by` varchar(30) DEFAULT NULL COMMENT '创建者',
  `update_at` varchar(24) DEFAULT NULL COMMENT '修改日期',
  `update_by` varchar(30) DEFAULT NULL COMMENT '修改者',
  `delete_at` varchar(24) DEFAULT NULL COMMENT '删除日期',
  `delete_by` varchar(30) DEFAULT NULL COMMENT '删除者',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='合作学习';
```
