### ISSUE TITLE
H5-学习系统: 私塾模块&词汇模块&课件学习模块- 第4阶段

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#482]
### 1. PC-Admin：基础数据  -`Kim`
- [x] 1.1 收集记录用户在每个课程上的实际学习时间。 具体细节， #386 #387    

<br>
<br>

### 2. 学习系统 - `David`
-  [ ]  2.1. H5-学习系统：课程播放页- 当前页可显示课件播放 & 习题 & 词汇学习 #436   - `P2` 
-  [ ]  2.2. H5-学习系统：课程播放页- 对视频课件可添加维护“知识点”标签   #439    - `P2`
```
```

<br>
<br>

### 3. 学习系统 - 词汇模块 -`Aaron`
-  [ ]  3.1. H5-学习系统: 词汇学习- Chapter&Lesson对应的词汇  #438  - `P3`

<br>
<br>

#### 6.1. 用户课程学习情况  
用户 | 课程 | Lesson | 开始学习时间 | 在线学习时长 | IP所在城市
-- | -- | -- | -- | -- | --

- [x]  6.1.1 用户课程学习课件的API #386
- [x]  6.1.2 AndroidAPP- 课件播放页： 调用 “课件学习时间”API        #463
- [ ]  6.1.3 H5-课件播放页： 调用 “课件学习时间”API
- [x]  6.1.4 iOSAPP-课件播放页：调用 “课件学习时间”API            #454

#### 6.2. PV & UV 
```
每天/月-某些页面(课程详情页 & 首页 & 课件播放页）：
PV（Page View）： 页面访问量
UV（Unique Visitor）：用户访问数 （没登入也算）

选择一个主流的来源统计分析平台，如Umeng等
```
##### 极光统计 SDK 文档：[Android](http://docs.jiguang.cn/janalytics/client/android_guide/)、[IOS](http://docs.jiguang.cn/janalytics/client/ios_guide/)

- [x]  6.2.1 AndroidAPP: 添加的跟踪PV&UV的代码            #463

```java
 // 页面统计
JAnalyticsInterface.onPageStart(this, this.getClass().getCanonicalName());
JAnalyticsInterface.onPageEnd(this, this.getClass().getCanonicalName());

 // 浏览事件
BrowseEvent bEvent = new BrowseEvent();
bEvent.setBrowseId(url);
bEvent.setBrowseName(title);
bEvent.setBrowseType("h5");
JAnalyticsInterface.onEvent(this, bEvent);
```
- [ ]  6.2.2 H5: 添加的跟踪PV&UV的代码
```
需要在被统计的页面 插入 `统计代码`:

现有课件播放页&登入页的统计代码:
<div style="display: none">
    <script src="https://s13.cnzz.com/z_stat.php?id=1261976258&web_id=1261976258" language="JavaScript" ></script>
</div>
```
- [x]  6.2.3 iOSAPP: 添加的跟踪PV&UV的代码        #454
```
必须配对调用beginLogPageView:和endLogPageView:两个函数来完成自动统计
启动SDK:
        let config = JANALYTICSLaunchConfig()
        config.appKey = JPUSHAppkey
        config.channel = RegisterChannel
        config.isProduction = isDeveloper.boolValue
        JANALYTICSService.setup(with: config)

pv:
        JANALYTICSService.startLogPageView(pageName)
        JANALYTICSService.stopLogPageView(pageName)

event:
        let browseEvent = JANALYTICSBrowseEvent()
        browseEvent.name = browseName
        browseEvent.contentID = path
        browseEvent.type = "h5"
        browseEvent.duration = duration
        JANALYTICSService.eventRecord(browseEvent)
```
